{
    "event_type": "segment.create.error",
    "timestamp": "2018-11-28 14:24:27.902437",
    "payload": {
        "masakari_object.name": "SegmentApiPayload",
        "masakari_object.data": {
            "service_type": "compute",
            "fault": {
                "masakari_object.name": "ExceptionPayload",
                "masakari_object.data": {
                    "module_name": "pymysql.err",
                    "exception": "DBError",
                    "traceback": "Traceback (most recent call last):\n  File \"/opt/stack/masakari/masakari/ha/api.py\", line ...",
                    "exception_message": "(pymysql.err.Internal Error) (1054, u\"Unknown column 'name' in 'field list'\" ...",
                    "function_name": "raise_mysql_exception"
                },
                "masakari_object.version": "1.0",
                "masakari_object.namespace": "masakari"
            },
            "recovery_method": "auto",
            "description": null,
            "name": "testT6"
        },
        "masakari_object.version": "1.0",
        "masakari_object.namespace": "masakari"
    },
    "priority": "ERROR",
    "publisher_id": "masakari-api:fake-mini",
    "message_id": "e5405591-1d19-4a8c-aa92-4d551165d863"
}